title: Muqi Zou
logo: /assets/img/muqi_pic2.jpg
resume_path: /assets/files/resume_muqizou.pdf
show_downloads: false
google_analytics: UA-152715299-1
theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-titles-from-headings
titles_from_headings:
  enabled: false
  strip_title: true # Optional: Prevents rendering the title twice if your theme already displays page.title
  collections: false # Optional: Enables the plugin for collection items

url: 'https://Muqi-Zou.github.io'

author: Muqi Zou

social_links:
  name: Muqi Zou
  email: "mailto:zou116@purdue.edu"
  github: "https://github.com/Muqi-Zou"
  linkedin: "https://www.linkedin.com/in/muqi-zou-96954a108/"
  google_scholar: "https://scholar.google.com/citations?user=mqP_lcgAAAAJ&hl=en&oi=ao"
